### ISSUE TITLE
All Spaces are replace for + in all links

### ISSUE THREAD

**Issue by LeonardoCruzRJ** [brendanheywood/moodle-local_cleanurls#120]
All spaces in all links are replace for '+' simbol, but the correct are replace for '-', what do i do?

**Comment by brendanheywood** [comment]
There are only 2 correct encodings for a space, + and %20. Using - is not correct and is not perfectly reversible. See:

https://en.wikipedia.org/wiki/Percent-encoding#The_application.2Fx-www-form-urlencoded_type

That said, in some places like the course urls you can specify exactly what you want by setting the course shortcode to exactly what you want including a - char.
