### ISSUE TITLE
Rewrite fails if $CFG->dirroot differs from Server Root

### ISSUE THREAD

**Issue by ndunand** [brendanheywood/moodle-local_cleanurls#19]
In that case, on [line 46 or router.php](https://github.com/brendanheywood/moodle-local_cleanurls/blob/master/router.php#L46), the value of the `$file` variable is wrong because:

- if Moodle is installed in `http://host.name/moodle`
- then `dirroot` will probably look like `/var/www/moodle`
- so `$file` will end up being equal to `dirroot + moodle_url->path`, which yields to `/var/www/moodle/moodle/path`, which is in turn never found

**Comment by ndunand** [comment]
What I can come up with (sorry for code ugliness)

    $subdirstoremove = count(explode('/', $CFG->wwwroot)) - 3;
    if ($subdirstoremove) {
        // i.e. $CFG->wwwroot is more than server root, one or more levels down
        while ($subdirstoremove > 0) {
            // for each of these levels, we remove it from dirroot as they're already taken into account in the moodle_url path ...
            $dirs = explode('/', $CFG->dirroot);
            array_pop($dirs);
            $dirroot = implode('/', $dirs);
            $subdirstoremove--;
        }
        // ... so we end up with the right file path:
        $file = $dirroot . $url->get_path();
    }
    else {
        $file = $CFG->dirroot . $url->get_path();
    }

**Comment by brendanheywood** [comment]
Thanks Nicolas - I thought I'd previously tested doing the directory mapping correction at the apache rewrite level, either way I need to document this better. If I do need to parse the wwwroot then moodle_url has a method to do this in one step without the while loop.

**Comment by brendanheywood** [comment]
Nicolas can you please pull the latest version and follow my updated instructions here:

https://github.com/brendanheywood/moodle-local_cleanurls#step-3-add-the-apache-rewrite-to-the-custom-router

and sanity check that this all works for you?
