### ISSUE TITLE
cleanurls break logo and profile pic

### ISSUE THREAD

**Issue by adigitalife** [brendanheywood/moodle-local_cleanurls#20]
I upgraded to 3.1+ the other day and tried (for the first time) to install cleanurls.  Unfortunately, it breaks the site's logo and user profile pic.  To test, I'm using the Clean theme (no modifications).

It appears to install correctly:
![screen shot 2016-06-23 at 08 28 12](https://cloud.githubusercontent.com/assets/960955/16292800/5994dbe8-391d-11e6-9d2d-961a07e4607e.png)

But when I save changes:
![screen shot 2016-06-23 at 08 28 56](https://cloud.githubusercontent.com/assets/960955/16292810/6f386b40-391d-11e6-9bdd-c62f95d4ac42.png)

Any ideas?  Might I have done something wrong?  By the way, I'm using .htaccess for the rewrite code but that shouldn't matter, right?

**Comment by brendanheywood** [comment]
Using it via .htaccess should be fine as long as it's functionally the same. Are you using the latest code on master? To help me debug this please provide the the urls generated for the two broken images and what they should be when cleaning is turned off, thanks :)

**Comment by adigitalife** [comment]
I downloaded the master from here right after the 3.1+ upgrade the other day.  So I think it should be the latest master.

Normally, this is the link to the logo: /pluginfile.php/1/theme_clean/smalllogo/-1/logo.jpg
And this is the link to the profile pic: /pluginfile.php/218/user/icon/clean/f2?rev=1

When cleaning is turned on, the logo: /pluginfile.php
And the profile pic: /pluginfile.php?rev=1

**Comment by brendanheywood** [comment]
Thanks for the info this should be sorted now, please give it a whirl.

**Comment by adigitalife** [comment]
Yes, it's fixed!  Thanks very much!
