### ISSUE TITLE
Problem with '&' in the shortname

### ISSUE THREAD

**Issue by adigitalife** [brendanheywood/moodle-local_cleanurls#21]
On my front page, "Turn editing on" breaks when cleaning is turned on.  It works fine for all the other course pages though.  The only difference I noticed is that the shortname for the site/frontpage contains an '&'.

To test, I removed the '&' and it worked.

**Comment by brendanheywood** [comment]
Hmm this was quite a deep bug right back in apache land. You will need to pull latest but also add the 'B' flag to the apache RewriteRule directive, I've updated the docs:

https://github.com/brendanheywood/moodle-local_cleanurls#step-3-add-the-apache-rewrite-to-the-custom-router
