### ISSUE TITLE
"Cleaner" category URLs

### ISSUE THREAD

**Issue by adigitalife** [brendanheywood/moodle-local_cleanurls#22]
This is a feature request.  Currently, categories are rewritten as /course/?categoryid=123.  I think it would look cleaner if they would instead be rewritten as /category/123.

I've only had a quick look at the code but I think I could figure this out on my own.  I'm not much of a coder though so it might take me awhile.  Lots of trial and error too. ;)

**Comment by brendanheywood** [comment]
It is just removing the redundant /index.php at the moment but nothing else. If I was going to rewrite categories I'd do it using the category idnumber, so if you had nested categories you could have a urls like:

```
/category/sciences/
/category/sciences/computing/
```

The only issue with this is that idnumber's for categories aren't required so we may want an admin option to turn this on, like usernames.

I'd also look into a fallback where if the id number field was empty it would create a pseudo url stub using the id and a human readable name which is actually ignored when routing eg:

```
/category/sciences-12/
/category/sciences-12/computing-34/
```

Please have a crack, and make sure to add the unit tests. I'm very open to pull requests :)

**Comment by brendanheywood** [comment]
I'm gonna start on this using the latter format

**Comment by brendanheywood** [comment]
Done! Please give this a whirl too :)

**Comment by adigitalife** [comment]
Nice! :)

**Comment by adigitalife** [comment]
By the way, would it be possible at some point to add that admin option to switch between with or without catid in the slug?  I don't know how to implement that myself.  For now, I've manually removed it on my site.  I just think /category/sciences/computing looks nicer.

**Comment by brendanheywood** [comment]
That is the intention, but I have a couple deep architectral changes I'd like to work on first so I can present a bunch of these choices in the admin gui when setting it up and a big refactoring of the mapping code into it's own engine with a declarative format. See #17
