### ISSUE TITLE
Changing course shortname causes an error

### ISSUE THREAD

**Issue by adigitalife** [brendanheywood/moodle-local_cleanurls#25]
If I edit the shortname of a course, a DB error occurs after I click save.  This is understandable since the old shortname is no longer found.  In a way, this is a good thing because it means the change was successfully saved.  However, doing a refresh doesn't fix the cleaned link, the old shortname is still in use.  I suppose it's cached somewhere since purging the cache resolves the issue.

Not sure how to fix this.  Perhaps if a DB error (shortname not found) is detected then it automatically purges the cache and refreshes the page?

**Comment by brendanheywood** [comment]
Yeah there are two levels to this, one is simply making the edit page go to the new url, which it should seamlessly. The second is what about if the old url has been bookmarked? The first can be hacked around, but if we want the second then I need to store a history of old urls and redirect / serve the current url. So which do you think?

**Comment by adigitalife** [comment]
For me, the first case is mandatory but the second case is more nice to have (albeit very cool).  I don't know how complicated it would be to implement the second case so I'd prioritize the first case.

Actually, the reason I proposed /category/123 in #22 is because of bookmarking.  Categories can easily be renamed and moved around so something like /category/biology might later become /category/science/biology.  So I thought /category/123 would be more consistent/permanent.

**Comment by brendanheywood** [comment]
I've fixed the first case cleanly, I'm still on the fence about the second. I'm not sure wether I should simply cache old urls mappings or store them in the db. It could become a very large amount of data essentially every url that you could visit. Conceptually I want it but operationally I want to avoid it. Anyway give it a test please :)

**Comment by adigitalife** [comment]
Works great!  As for the second case, I wouldn't be too sure either.  I mean, where do you draw the line?  Would the plugin then need to keep track of every past shortname?  Or would there be a cut-off and regular cleanup?  It would also then need to keep track of deleted courses as part of the cleanup.

**Comment by brendanheywood** [comment]
I'd probably do some storage of the last time it was used and delete mappings which haven't been used in a certain period. But yeah I will hold off on doing this
