### ISSUE TITLE
Admin option to purge clean URL cache

### ISSUE THREAD

**Issue by adigitalife** [brendanheywood/moodle-local_cleanurls#26]
Would it be possible to add in the admin settings an option to purge the clean URL cache?  I was playing around a bit and I noticed that I needed to purge the cache after making some code changes.  So I was thinking it would be nice to be able to purge just the cache for clean URLs.  That way, I don't lose the cache for the rest of the site.

**Comment by brendanheywood** [comment]
This is not actually possible with moodle's cache api. You either need to know all the cache keys to clear or you clear everything. Things like a course shortcode rename should cascade clear all the activitiy urls inside the course but to do that properly I'm going to have to go look them all up first in the DB, I can't get that info from the cache store itself.

As a workaround you can make a new cache store definition, eg have one memcache for all the usual app cache stuff and then a second memcache instance for just the url mappings and clear it via the cache store admin gui. Note that if you use memcache stores they have to be completely different instances and not just a key prefix as memcache itself can't do that. Redis and some other stores can.
