### ISSUE TITLE
Rewrite router test file not found

### ISSUE THREAD

**Issue by dannyjung90** [brendanheywood/moodle-local_cleanurls#27]
Visiting the settings page generates the an error in my apache log that says local/cleanurls/tests/file does not exist. Adding .php to the end of the path fixed the error for me, but I'm not sure if this plugin is supposed to be able to figure out that local/cleanurls/tests/file is actually local/cleanurls/tests/file.php.

**Comment by brendanheywood** [comment]
@roperto I'm pretty sure you've already fixed this one?
