### ISSUE TITLE
Rewrite router is NOT working

### ISSUE THREAD

**Issue by nawrasgh** [brendanheywood/moodle-local_cleanurls#3]
I am getting this error message 'Rewrite router is NOT working'
any advise?

another question : can we add these into .htaccess  instead of apache?
RewriteEngine on
   RewriteBase /
   RewriteCond %{REQUEST_FILENAME} !-f
   RewriteCond %{REQUEST_FILENAME} !-d
   RewriteRule ^(.*)$ local/cleanurls/router.php?q=$1 [L,QSA]

**Comment by brendanheywood** [comment]
I'll add a more detailed write up into the readme in a debugging section, but short answer is make sure mod_rewrite is enabled, and turn on full rewrite debugging to see why the rewrite in apache isn't working. It's possibly that the rewrite is but the test is returning a false negative. We are working on ironing out all the bugs and will get this submitted into the plugin directory once they are sorted

**Comment by brendanheywood** [comment]
I've added some more details into:

https://github.com/brendanheywood/moodle-local_cleanurls#step-3-add-the-apache-rewrite-to-the-custom-router

I don't think there is anything code wise to fix here so I'm closing this

**Comment by dewebmeester** [comment]
Sorry for bothering. See this is closed but still do not see an answer to the question: "can we add these into .htaccess instead of apache" - Not clear where to add the strings mentioned in Step 3. Is it indeed an option to add an htaccess file to the moodle root and place the strings there (tried already but dit not function - got me a 500 error).

**Comment by brendanheywood** [comment]
Yes apache accepts config in htaccess or a .conf file in exactly the same way unchanged, as long as htaccess is turned on. I've added an example to the docs:

https://github.com/brendanheywood/moodle-local_cleanurls#step-3-add-the-apache-rewrite-to-the-custom-router
