### ISSUE TITLE
Plugin tester on settings page is giving false positives

### ISSUE THREAD

**Issue by ioannakan** [brendanheywood/moodle-local_cleanurls#33]
Hello,
i installed the plugin succesfully, i get the two green messages but the urls are not changed. Anywhere in the platform. I am running Moodle 3.0.5, apache 2.4, i don't use .htaccess and the apache's error.log doesn't give me anything useful.
 Any ideas?

Thank you in advance,
Ioanna

**Comment by brendanheywood** [comment]
The hooks enabling this plugin to work only landed in 3.1, but you can manually path 3.0 to allow it, did you follow this step?

https://github.com/brendanheywood/moodle-local_cleanurls#step-2-apply-tiny-patches-to-core

**Comment by ioannakan** [comment]
thanks for your quick answer.
Yes i followed it, and when i did the green message "Rewrite router is working" appeared, so that means that it was enabled right?

**Comment by brendanheywood** [comment]
Yes it should in theory. There is a very slim possible there is still an issue with the router and the test is returning a false positive, it's an edge case that could happen if you are using content negotiation so I've just rewritten the test to be a little more robust. So you can pull the latest master and give that a whirl. You can also turn on the debug logging inside the local plugins settings page which dumps a whole heaps of stuff into the apache error log. Can you give some example course or module urls you are trying to clean?

**Comment by ioannakan** [comment]
Hello,
i just want the courses urls to clean. e.g. http://class.future-farmer.eu/course/view.php?id=5 .

I uninstalled the plugin to give it a try from the beginning in order to do all the steps again. I will come back when i will have news or something useful from the logs. I was also thinking upgrading first to Moodle 3.1 and then install it again. What do you think?

**Comment by brendanheywood** [comment]
The moodle version won't make a different. After you have installed it again (I can see it's missing at the moment) go to a random url like this:

http://class.future-farmer.eu/something-random

then this should go through the apache rewrite, get passed to the /local/cleanurls/router.php file, and then result in a 'nice' 404 error because it doesn't map to a moodle url. If not then double check that you have installed the rewrite correctly and bounced apache

**Comment by ioannakan** [comment]
Hello,
i installed it again but it still doesn't work. I am sending you the logs (sorry for that but i cannot attach files):

[Tue Oct 18 17:20:36.353221 2016] [:error] [pid 17386] [client] Router: $_GET: 'local/cleanurls/tests/bar'
[Tue Oct 18 17:20:36.353289 2016] [:error] [pid 17386] [client  ] Incoming url: http://class.future-farmer.eu/local/cleanurls/tests/bar
[Tue Oct 18 17:20:36.353333 2016] [:error] [pid 17386] [client  ] Incoming path: /local/cleanurls/tests/bar
[Tue Oct 18 17:20:36.353364 2016] [:error] [pid 17386] [client  ] Rewritten to: /local/cleanurls/tests/foo.php
[Tue Oct 18 17:20:36.353389 2016] [:error] [pid 17386] [client  ] Rewritten to: /local/cleanurls/tests/foo.php
[Tue Oct 18 17:20:36.353426 2016] [:error] [pid 17386] [client  ] Router: including file: /var/www/html/local/cleanurls/tests/foo.php
[Tue Oct 18 17:22:09.345820 2016] [:error] [pid 15933] [client  ] Router: $_GET: 'something-random'
[Tue Oct 18 17:22:09.345907 2016] [:error] [pid 15933] [client  ] Incoming url: http://class.future-farmer.eu/something-random
[Tue Oct 18 17:22:09.345966 2016] [:error] [pid 15933] [client  ] Incoming path: /something-random
[Tue Oct 18 17:22:09.346049 2016] [:error] [pid 15933] [client  ] Rewritten to: /something-random.php
[Tue Oct 18 17:22:09.346088 2016] [:error] [pid 15933] [client  ] Router: including file: /var/www/html/something-random.php
[Tue Oct 18 17:22:09.346133 2016] [:error] [pid 15933] [client  ] Router: Not found, showing 404 instead: /var/www/html/something-random.php

**Comment by brendanheywood** [comment]
Ok so the inbound router is definitely working fine, it's just the outbound links that moodle is rendering aren't. eg this url using the shortcode works:

http://class.future-farmer.eu/course/bbe

The outbound links are still not being rewritten through, I've just pushed another commit to master which makes this testing a bit more robust so hopefully it will at least correctly detect the issue now. Can you please grab install that latest code and send me a screen shot of /admin/settings.php?section=local_cleanurls

**Comment by ioannakan** [comment]
Hello Brendan,
Thank you so so much for your help.
I am sending you the screenshots. In settings page it appears the message that I haven’t added the appropriate code at the config.php but I do have! 

![config](https://cloud.githubusercontent.com/assets/12711611/19511522/33fcd43c-95f0-11e6-8528-f1349a6cf007.JPG)
![settings](https://cloud.githubusercontent.com/assets/12711611/19511537/41690802-95f0-11e6-93c9-c6ab19086857.JPG)

**Comment by brendanheywood** [comment]
Ok so I've just fixed tweaked that error detection to be a bit more useful, it now detects whether it's a config issue vs a hook issue. In your case I'm pretty sure it's a hook issue so you can pull the latest to confirm that, if so you'd see this new error message:

![image](https://cloud.githubusercontent.com/assets/187449/19539640/2e3bcbdc-96a6-11e6-9a72-ad89212e6929.png)

Can you double check you've correctly applied the backport patch for 3.0 by running this:

```bash
grep -n urlrewriteclass lib/weblib.php 
564:        if (isset($CFG->urlrewriteclass) && !isset($CFG->upgraderunning)) {
565:            $class = $CFG->urlrewriteclass;
```

If that grep doesn't find anything then re apply the back port patch for the hooks needed for this plugin to work (which assumes you have used git to clone moodle?), or failing that then your suggestion to upgrade to 3.1 should also work:

https://github.com/brendanheywood/moodle-local_cleanurls#step-2-apply-tiny-patches-to-core

**Comment by brendanheywood** [comment]
@ioannakan any luck sorting this?

**Comment by ioannakan** [comment]
Hello Brendan,
no luck yet... I am applying the patch but nothing. It is true that i haven't clone moodle from git. I am going to do the update to 3.1 soon, that is why i hadn't answer. As soon as i have news , i will communicate. Thanks again for everything

**Comment by ioannakan** [comment]
Hello!!! I updated moodle to 3.1 at my development server and the plugin works like a charm :) Soon i will update it in production.

Thanks a lot for all your help.

Best regards,
Ioanna
