### ISSUE TITLE
Special characters in activity names

### ISSUE THREAD

**Issue by merrill-oakland** [brendanheywood/moodle-local_cleanurls#4]
Special chars (like %) aren't stripped out of name in the URL. If an activity ends in a % it will throw a fatal error.

Since we aren't actually using the name, we should just strip all but the most basic characters.

**Comment by brendanheywood** [comment]
Ok so what should happen is the render url's should be written as:

For a course with a short code of 'COMP101%yay' this should be url encoded as:

http://moodle.local/course/COMP101%25yay
