### ISSUE TITLE
Some tests are red, travis not executing unit tests.

### ISSUE THREAD

**Issue by roperto** [brendanheywood/moodle-local_cleanurls#41]
Some tests are RED and were not detected by Travis.

**Comment by roperto** [comment]
We are back to green in development, will merge into master with the fix for issue #40 .

**Comment by brendanheywood** [comment]
Can you please:

* [ ] add a test to cover 8f633f133 and
* [ ] add back in travis support for all the old moodle's using this feature: (chat to @kenneth-hendricks if you want an example)

https://github.com/moodlerooms/moodle-plugin-ci/issues/34

**Comment by kenneth-hendricks** [comment]
Just a heads up - my patch hasn't hit packagist yet. you can either wait for that or change your .travis.yml before_install and env to match: https://github.com/catalyst/moodle-tool_sssfs/blob/c2d30af7c5300de15d9e823511a5c7c91db09fca/.travis.yml

**Comment by roperto** [comment]
What about applying the patches provided in cleanurls repo after the install in Travis?

If it works, it would also test the patches in the process.

**Comment by roperto** [comment]
We are green in development, testing Moodle 29+30 (with core patch) + vanilla 31, 32 and master.
