### ISSUE TITLE
Moodle internal redirection breaks when using relative paths.

### ISSUE THREAD

**Issue by roperto** [brendanheywood/moodle-local_cleanurls#42]
We found this particular example:

1) Create an assignment with feedback files enabled.

2) Submit a file as feedback for a student (select one or more)

3) The redirection should fail after saving the file.

**Comment by roperto** [comment]
Moodle already converts relative to absolute in case of redirection, but unaware of cleanurls it uses the requested URL as the base path.

More specificaly: https://github.com/moodle/moodle/blob/f31e1e8b258eb89ae43a73d0a9bda41e49581edd/lib/weblib.php#L2763

In the `me()` call, it may change the location we currently are.

The proposed solution (see commit above) is to make ALL URLs absolute when using clean urls (we cannot detect if it is a redirect).

@brendanheywood if you can please review it carefully as it would affect all URLs parsed by the cleaner. 

Thanks

**Comment by roperto** [comment]
The previous code was not working when calling a legacy URL that could be replaced. It failed because it could not find the base href.

The commit https://github.com/brendanheywood/moodle-local_cleanurls/commit/0e34e1f751315ed043a0ded6f86fdee479720bec addressed that issue.

**Comment by brendanheywood** [comment]
Some thing doesn't feel right with this. Can you document the exact problem with example urls

This line in particular bugs me:

https://github.com/brendanheywood/moodle-local_cleanurls/commit/0e34e1f751315ed043a0ded6f86fdee479720bec#diff-4a1049c26c3a1096dbfa2c9c9c6468f0R66

I can't see when this would ever get triggered? Also none of this has any tests, in particular tests which include an install inside a directory.

**Comment by roperto** [comment]
The commit above fixes the $ME variable so it is not needed to make all URLs absolute.

The previous branch - issue42-makeabsolute - will be deleted without merging.
