### ISSUE TITLE
URL after uninstalling the module cleanurls

### ISSUE THREAD

**Issue by San4euS** [brendanheywood/moodle-local_cleanurls#50]
Hello!
I used this module.
After 1 month of use, I deleted it.
It has already been a long time, but in the webmaster. Google still does not exist URL (http://100ballov.kz/course/%D0%9C%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0+10+%D0%BA%D0%BB%D0%B0%D1%81%D1%81/page/763-%D0%9A%D0%BE%D0%BC%D0%B1%D0%B8%D0%BD%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D0%BA%D0%B0-%D0%B8-%D0%B2%D0%B5%D1%80%D0%BE%D1%8F%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C.-%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D1%84%D0%BE%D1%80%D0%BC%D1%83%D0%BB)

Tell me what I did wrong?

**Comment by brendanheywood** [comment]
So from looking at that very long url which contains a bunch of unicode characters which I'm guessing is russian?

http://100ballov.kz/course/Математика+10+класс/page/763-Комбинаторика-и-вероятность.-Применение-формул

Can you clarify the exact symptom? ie was it:

1) the url didn't work and load a moodle page?
2) the url did work but google never indexed it?
