### ISSUE TITLE
Cases where page is already using a 'q' parameter.

### ISSUE THREAD

**Issue by roperto** [brendanheywood/moodle-local_cleanurls#58]
Another edge case

/search.php?q=search

which gets cleaned

both it and the router.php use q as the query param

**Comment by brendanheywood** [comment]
This should not be an issue if the url escaping is done right. I think the way we pass arguments back into the router is probably quite wrong. 

Ie if the incoming url is

/search.php?q=search

then this should be encoded verbatum as

%2Fsearch.php%3Fq%3Dsearch

and then sent to the router via:

/router.php?q=%2Fsearch.php%3Fq%3Dsearch

There are multiple edge cases where doing it the current way will break stuff, eg if the query string is assumed to be in a certain order, or duplicate params or valueless params etc all of which are perfectly valid. Nginx / apache should not be touching the params at all and they should be character perfect when unencoded on the other side at the app level.

**Comment by roperto** [comment]
For now the 'q' parameter will get overwritten. There could be other approaches, but a simple one would be using `local_cleanurls_src` or something like that instead of `q`. That would minimise the change of collision and this replacement is all done server-side, so it wouldn't have side effects on the browser.

**Comment by brendanheywood** [comment]
From internal discussion, we can:

* quick fix: renaming the variable)
* elegant fix: encoding the whole url (like apache does but nginx does not)
* no-fix: theoretical as nowhere in core actually causes this issue

For no we will do no-fix until it bites us somewhere
