### ISSUE TITLE
Support section level routing dependent on the course format

### ISSUE THREAD

**Issue by brendanheywood** [brendanheywood/moodle-local_cleanurls#59]
So some example urls and course formats:

1) we have the 'Single_activity_format' in which case the whole course is one activity. In this case there is no need for a url stub and the entire could be /course/COMP100

2) we have a course with a single section0 and everything in it. So there is no extra level and the urls might be /course/COMP100/activity

3) we have a standard course which has sections like 'week1' and so the urls might be /course/COMP100/week1/activity

4) we have a complex course format like flexi format which has N levels of nested sections so the url could be /course/COMP100/module1/topic2/activity

So obvious the logic around the middle section of the url needs to be based on the course format. We may also have some default rules in place which cover the standard formats but this is lower priority.

So proposing to have an optional call back inside each course format which is provided with a url component and it returns a list of known matches sections.

So the whole process might look something like:

1) the router gets a url like this:
/course/COMP100/module1/topic2/activity

It parses the first components and matches /course/.*/, then chops that off and recognises COMP100 as a valid course.

2) now that it knows the course it looks up the course format, and in this case it is set to flexi

3) Next it parses the remainder of the url "module1/topic2/activity" into ["module1", "topic2", "activity"] and passes this to a callback provided by the flexi format which attempts to parse each stub into a section id. In this case it might match the first 2 and return an array like [[37, url1], [89, url2]] which means it has found 2 levels of matching section id's. We do not want the burden on the formats to be high so as much of the preparsig is done for it. And it should not have to deal with anything outside the scope of sections.

4) now the main cleanurls knows that it should look for an activity with a stub of "activity" inside the section with an id of 89. If it finds that then we are all good, if not send a 404.

5) lets say that the format matched every single section id, this means we are on a section url and not an activity url. In which case we need to unclean the url internally and pass it back to the format to render. The course format can declare a url like this:

http://moodle.prod.local/course/view.php?id=2&section=1

This is why in the callback it will return both an section id and a url.

6) If the course format doesn't declare a callback then for the time being lets do what we currently do, ie there is no middle slub component. But we might be able to do something better in future.

NOTE: I do not believe there is an easy way to extend the course format form to add an extra field for an explicit slug. So this means we may have to 'search' the sections in a course and return the best match. ie if the section name is "Week 1" then this could be simplified into "week-1" but then this could also match potentially many sections. Also I do not think there is any guarantee of uniqueness across section titles, so we will just pick the first one. It would be good to get the 'sluggify' logic implemented in sql so we can search and match in a single sql query instead of coming back and forth into php land.

**Comment by brendanheywood** [comment]
See also https://github.com/brendanheywood/moodle-local_cleanurls/issues/35

**Comment by roperto** [comment]
This one is implemented (slightly different way) with #61.

**Comment by roperto** [comment]
Implemented.
